make layouts list in alphabetical order
fredy20501/AttendanceTracker pull request #51
Opened 2020-11-26 13:48 UTC by PEKennedy

Update the createSectionLayout page to list available layouts in alphabetical order.

Needs review.

2020-11-26 23:39 UTC, fredy20501 requested changes
This looks good! Note that we also want to sort the sections on the dashboard, so you can add something similar in `Dashboard.vue` in the `getSections()` function after we get the data and in the `registerForSection()` after we insert a new section in the list.

2020-11-28 00:48 UTC, ravenmills3 requested changes
Good but should also be applied to how sections are displayed in the dashboard view

2020-11-28 01:51 UTC, fredy20501 approved these changes

2020-11-30 02:08 UTC, ravenmills3 approved these changes

2020-11-30 02:08 UTC, merged